ALTER TABLE users ADD COLUMN IF NOT EXISTS social_links JSONB DEFAULT '[]';
ALTER TABLE users ADD COLUMN IF NOT EXISTS availability_status VARCHAR(30) DEFAULT 'not_set';
ALTER TABLE users ADD COLUMN IF NOT EXISTS availability_label VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS thankyou_message VARCHAR(200);
ALTER TABLE users ADD COLUMN IF NOT EXISTS accent_color VARCHAR(20) DEFAULT 'amber';
